### PR TITLE
#9 fix colouring

### LINKED ISSUE #11: fix colouring

### PR DESCRIPTION
**Pull request by AndrzejLech**

### CODE REVIEW

File: src/app/components/common-timetable/timetable/timetable.component.ts [hunk 1]
```diff
@@ -88,17 +88,16 @@ export class TimetableComponent implements OnInit {
...
-    let mfzDayName = mfzDay.name
-    let mfzDayBusyStatus = mfzDay.isBusy;
     for (let week of this.nurWeeks) {
-      for (let day of week.days) {
-        if (day.name === mfzDayName) {
-          let nurDayBusyStatus = day.isBusy
-          return nurDayBusyStatus === mfzDayBusyStatus
+      for (let nurDay of week.days) {
+        if (nurDay.name === mfzDay.name) {
+          console.log(nurDay.name, nurDay.isBusy, mfzDay.isBusy)
```
Comment (PythSomeone) [inline src/app/components/common-timetable/timetable/timetable.component.ts]: remove console log, please

**Review by PythSomeone — CHANGES_REQUESTED** [review]
remove console log

File: src/app/components/common-timetable/timetable/timetable.component.ts (hunk 1 above)
Comment (AndrzejLech) [reply src/app/components/common-timetable/timetable/timetable.component.ts]: done

**Review by PythSomeone — APPROVED** [review]
